[tool.poetry]
name = "olas-operate-app"
version = "0.2.0-rc182"
description = ""
authors = ["David Vilela <dvilelaf@gmail.com>", "Viraj Patel <vptl185@gmail.com>"]
readme = "README.md"
packages = []
include = []

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
olas-operate-middleware = { git = "https://github.com/valory-xyz/olas-operate-middleware.git", rev = "c71a9d34492c01676696a9a13f5ea167349aa390"}
dune-client = "^1.7.9"
pandas = "^2.3.0"
tqdm = "^4.67.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
