[tool.poetry]
name = "olas-operate-app"
version = "0.2.0-rc187"
description = ""
authors = ["David Vilela <dvilelaf@gmail.com>", "Viraj Patel <vptl185@gmail.com>"]
readme = "README.md"
package-mode = false
packages = []
include = []

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
olas-operate-middleware = { git = "https://github.com/valory-xyz/olas-operate-middleware.git", rev = "295e4bb9b144bf087caa7321599fc9f24552767d"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
